In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
links=pd.read_csv("/content/links.csv")
links.head(5)

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [ ]:
ratings=pd.read_csv("/content/ratings.csv")
ratings.head(5)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [ ]:
ratings['userId'].nunique()
ratings['movieId'].nunique()

9724

In [ ]:
tags=pd.read_csv("/content/tags.csv")
tags.head()

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [ ]:
movies=pd.read_csv("/content/movies.csv")
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
df=pd.merge(ratings,movies,on='movieId')

In [ ]:
df.head(5)

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [ ]:
user_movie=df.pivot_table(
    index='userId',
    columns='title',
    values='rating'
)

In [ ]:
user_movie=user_movie.fillna(0)
print(user_movie)

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId
1              0.0                                      0.0
2              0.0                                      0.0
3              0.0                                      0.0
4              0.0                                      0.0
5              0.0                                      0.0
...            ...                                      ...
606            0.0                                      0.0
607            0.0                                      0.0
608            0.0                                      0.0
609            0.0                                      0.0
610            4.0                                      0.0

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId
1                          0.0                  0.0
2                          0.0                  0.0
3                          0.0                  0.0
4                          0.0                  0.0
5                          0.0                  0.0
...                        ...                  ...
606                        0.0                  0.0
607                        0.0                  0.0
608                        0.0                  0.0
609                        0.0                  0.0
610                        0.0                  0.0

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId
1                             0.0                              0.0
2                             0.0                              0.0
3                             0.0                              0.0
4                             0.0                              0.0
5                             0.0                              0.0
...                           ...                              ...
606                           0.0                              0.0
607                           0.0                              0.0
608                           0.0                              0.0
609                           0.0                              0.0
610                           0.0                              0.0

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId
1                      0.0                   0.0                          0.0
2                      0.0                   0.0                          0.0
3                      0.0                   0.0                          0.0
4                      0.0                   0.0                          0.0
5                      0.0                   0.0                          0.0
...                    ...                   ...                          ...
606                    0.0                   0.0                          0.0
607                    0.0                   0.0                          0.0
608                    0.0                   0.0                          0.0
609                    0.0                   0.0                          0.0
610                    0.0                   0.0                          3.5

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...
1                                  0.0  ...          0.0           0.0
2                                  0.0  ...          0.0           0.0
3                                  0.0  ...          0.0           0.0
4                                  0.0  ...          0.0           0.0
5                                  0.0  ...          0.0           0.0
...                                ...  ...          ...           ...
606                                0.0  ...          0.0           0.0
607                                0.0  ...          0.0           0.0
608                                0.0  ...          0.0           0.0
609                                0.0  ...          0.0           0.0
610                                0.0  ...          0.0           4.0

title   [REC]² (2009)  [REC]³ 3 Génesis (2012)  \
userId
1                 0.0                      0.0
2                 0.0                      0.0
3                 0.0                      0.0
4                 0.0                      0.0
5                 0.0                      0.0
...               ...                      ...
606               0.0                      0.0
607               0.0                      0.0
608               0.0                      0.0
609               0.0                      0.0
610               3.5                      3.0

title   anohana: The Flower We Saw That Day - The Movie (2013)  \
userId
1                                                     0.0
2                                                     0.0
3                                                     0.0
4                                                     0.0
5                                                     0.0
...                                                   ...
606                                                   0.0
607                                                   0.0
608                                                   0.0
609                                                   0.0
610                                                   0.0

title   eXistenZ (1999)  xXx (2002)  xXx: State of the Union (2005)  \
userId
1                   0.0         0.0                             0.0
2                   0.0         0.0                             0.0
3                   0.0         0.0                             0.0
4                   0.0         0.0                             0.0
5                   0.0         0.0                             0.0
...                 ...         ...                             ...
606                 0.0         0.0                             0.0
607                 0.0         0.0                             0.0
608                 4.5         3.5                             0.0
609                 0.0         0.0                             0.0
610                 0.0         2.0                             1.5

title   ¡Three Amigos! (1986)  À nous la liberté (Freedom for Us) (1931)
userId
1                         4.0                                        0.0
2                         0.0                                        0.0
3                         0.0                                        0.0
4                         0.0                                        0.0
5                         0.0                                        0.0
...                       ...                                        ...
606                       0.0                                        0.0
607                       0.0                                        0.0
608                       0.0                                        0.0
609                       0.0                                        0.0
610                       0.0                                        0.0

[610 rows x 9719 columns]

In [ ]:
similarity=cosine_similarity(user_movie)

similarity_df=pd.DataFrame(similarity, index=user_movie.index,
                          columns=user_movie.index)
print(similarity_df)

userId       1         2         3         4         5         6         7    \
userId
1       1.000000  0.027283  0.059720  0.194395  0.129080  0.128152  0.158744
2       0.027283  1.000000  0.000000  0.003726  0.016614  0.025333  0.027585
3       0.059720  0.000000  1.000000  0.002251  0.005020  0.003936  0.000000
4       0.194395  0.003726  0.002251  1.000000  0.128659  0.088491  0.115120
5       0.129080  0.016614  0.005020  0.128659  1.000000  0.300349  0.108342
...          ...       ...       ...       ...       ...       ...       ...
606     0.164191  0.028429  0.012993  0.200395  0.106435  0.102123  0.200035
607     0.269389  0.012948  0.019247  0.131746  0.152866  0.162182  0.186114
608     0.291097  0.046211  0.021128  0.149858  0.135535  0.178809  0.323541
609     0.093572  0.027565  0.000000  0.032198  0.261232  0.214234  0.090840
610     0.145321  0.102427  0.032119  0.107683  0.060792  0.052668  0.193219

userId       8         9         10   ...       601       602       603  \
userId                                ...
1       0.136968  0.064263  0.016875  ...  0.080554  0.164455  0.221486
2       0.027257  0.000000  0.067445  ...  0.202671  0.016866  0.011997
3       0.004941  0.000000  0.000000  ...  0.005048  0.004892  0.024992
4       0.062969  0.011361  0.031163  ...  0.085938  0.128273  0.307973
5       0.429075  0.000000  0.030611  ...  0.068048  0.418747  0.110148
...          ...       ...       ...  ...       ...       ...       ...
606     0.099388  0.075898  0.088963  ...  0.178084  0.116534  0.300669
607     0.185142  0.011844  0.010451  ...  0.092525  0.199910  0.203540
608     0.187233  0.100435  0.077424  ...  0.158355  0.197514  0.232771
609     0.423993  0.000000  0.021766  ...  0.035653  0.335231  0.061941
610     0.078153  0.074399  0.121072  ...  0.222491  0.087528  0.163094

userId       604       605       606       607       608       609       610
userId
1       0.070669  0.153625  0.164191  0.269389  0.291097  0.093572  0.145321
2       0.000000  0.000000  0.028429  0.012948  0.046211  0.027565  0.102427
3       0.000000  0.010694  0.012993  0.019247  0.021128  0.000000  0.032119
4       0.052985  0.084584  0.200395  0.131746  0.149858  0.032198  0.107683
5       0.258773  0.148758  0.106435  0.152866  0.135535  0.261232  0.060792
...          ...       ...       ...       ...       ...       ...       ...
606     0.066032  0.148141  1.000000  0.153063  0.262558  0.069622  0.201104
607     0.137834  0.118780  0.153063  1.000000  0.283081  0.149190  0.139114
608     0.155306  0.178142  0.262558  0.283081  1.000000  0.121993  0.322055
609     0.236601  0.097610  0.069622  0.149190  0.121993  1.000000  0.053225
610     0.052552  0.119295  0.201104  0.139114  0.322055  0.053225  1.000000

[610 rows x 610 columns]

In [ ]:
user_id=1

In [ ]:
similar_users=similarity_df[user_id].sort_values(ascending=False)[1:6]
print(similar_users)

userId
266    0.357408
313    0.351562
368    0.345127
57     0.345034
91     0.334727
Name: 1, dtype: float64

In [ ]:
movie=user_movie.loc[similar_users.index]
print(movie.head())

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId
266            0.0                                      0.0
313            0.0                                      0.0
368            0.0                                      0.0
57             0.0                                      0.0
91             0.0                                      0.0

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId
266                        0.0                  0.0
313                        0.0                  0.0
368                        0.0                  0.0
57                         0.0                  0.0
91                         0.0                  0.0

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId
266                           0.0                              0.0
313                           0.0                              0.0
368                           0.0                              0.0
57                            0.0                              0.0
91                            0.0                              0.0

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId
266                    0.0                   0.0                          0.0
313                    0.0                   0.0                          0.0
368                    0.0                   0.0                          0.0
57                     0.0                   0.0                          0.0
91                     2.0                   0.0                          0.0

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...
266                                0.0  ...          0.0           0.0
313                                0.0  ...          0.0           0.0
368                                0.0  ...          0.0           0.0
57                                 0.0  ...          0.0           0.0
91                                 0.0  ...          0.0           0.0

title   [REC]² (2009)  [REC]³ 3 Génesis (2012)  \
userId
266               0.0                      0.0
313               0.0                      0.0
368               0.0                      0.0
57                0.0                      0.0
91                0.0                      0.0

title   anohana: The Flower We Saw That Day - The Movie (2013)  \
userId
266                                                   0.0
313                                                   0.0
368                                                   0.0
57                                                    0.0
91                                                    0.0

title   eXistenZ (1999)  xXx (2002)  xXx: State of the Union (2005)  \
userId
266                 0.0         0.0                             0.0
313                 0.0         0.0                             0.0
368                 0.0         0.0                             0.0
57                  0.0         0.0                             0.0
91                  0.0         0.0                             0.0

title   ¡Three Amigos! (1986)  À nous la liberté (Freedom for Us) (1931)
userId
266                       0.0                                        0.0
313                       1.0                                        0.0
368                       0.0                                        0.0
57                        2.0                                        0.0
91                        0.0                                        0.0

[5 rows x 9719 columns]

In [ ]:
recommended = movie.mean().sort_values(ascending=False)

print(recommended.head())

title
Aliens (1986)                                                                     4.8
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    4.8
Matrix, The (1999)                                                                4.8
Saving Private Ryan (1998)                                                        4.7
Usual Suspects, The (1995)                                                        4.5
dtype: float64

In [ ]:
watched = user_movie.loc[user_id]

recommended = recommended[watched == 0]

In [ ]:
print(recommended.head(5))

title
Aliens (1986)                       4.8
Hunt for Red October, The (1990)    4.3
Blade Runner (1982)                 4.0
Godfather, The (1972)               4.0
Die Hard (1988)                     4.0
dtype: float64

In [ ]:
import pickle

In [ ]:
pickle.dump(user_movie,open("user_movie.pkl", "wb"))
pickle.dump(similarity_df,open("similarity.pkl","wb"))
print("model saved")

model saved